Feature/simgan support block code
ezCGP/ezCGP pull request #127
Opened 2021-02-02 19:52 UTC by adachille

https://github.com/ezCGP/ezCGP/issues/123

2021-02-02 23:04 UTC, roddtalebi requested changes
welp im impressed by how quickly you got into the swing of things . nice

2021-02-02 23:04 UTC, roddtalebi commented on problems/problem_tfkeras_transferlearning.py
> +        # assert(len(tf.config.experimental.list_physical_devices('GPU'))>=1), "GPU NOT FOUND - ezCGP EXITING"
woops sorry

2021-02-03 20:55 UTC, adachille commented on codes/block_definitions/block_evaluate.py
> +    @abstractmethod
Ah good, thanks for letting me know.

2021-02-03 20:55 UTC, adachille commented on codes/block_definitions/block_evaluate.py
> +        import pdb; pdb.set_trace()
Good catch

2021-02-03 20:58 UTC, adachille commented on codes/block_definitions/block_evaluate.py
> +                node = function(inputs[-1], *args)
Hm, this is something I would like to talk to you about more. I want to figure out a way to allow for more than 1 input, but I'm just not 100% sure what that looks like.

2021-02-05 21:43 UTC, adachille commented
I changed the code so that every operator is a subclass of PyTorchLayerWrapper. This makes everything much much simpler, allows for multiple inputs (even if not all are utilized), and makes building graphs easy!

2021-02-10 19:56 UTC, roddtalebi approved these changes
i never really liked nn.Sequential for building a graph but I think i can see what is happening and how it works. you have my blessings.

2021-02-10 19:56 UTC, merged